### ISSUE TITLE
parallel running of input load, metrics, output

### ISSUE THREAD

**Issue by tooptoop4** [YotpoLtd/metorikku#128]
can running of various input dataframes be done in parallel? similar with metrics, or outputs?

**Comment by lyogev** [comment]
Hi, can you elaborate a bit?

**Comment by tooptoop4** [comment]
example:
inputs:
  movies:
    file_date_range:
      template: examples/file_date_range_inputs/%s/movies.csv
      date_range:
        format: yyyy/MM/dd
        startDate: 2017/09/01
        endDate: 2017/09/03
  ratings:
    file:
      path: examples/file_inputs/ratings.csv

I would like dataframes for movies and ratings to be loaded in parallel, without load of ratings having to wait for load of movies.


steps:
- dataFrameName: moviesWithRatings
  sql:
    SELECT userid,
           movies.movieid,
           rating,
           timestamp,
           title,
           genres
    FROM ratings
    JOIN movies ON ratings.movieid = movies.movieid
- dataFrameName: fantasyMovies
  sql:
    SELECT movieId
    FROM movies
    WHERE genres LIKE '%Fantasy%'
output:
- dataFrameName: moviesWithRatings
  outputType: Parquet
  outputOptions:
    saveMode: Overwrite
    path: moviesWithRatings.parquet
- dataFrameName: fantasyMovies
  outputType: Parquet
  outputOptions:
    saveMode: Overwrite
    path: fantasyMovies.parquet

I would like metric sql of fantasyMovies to run at same time of moviesWithRatings metric sql. Similarly for outputs would like the 2 outputs to be done concurrently

**Comment by lyogev** [comment]
Thanks for explaining.
Steps in metorikku will be done in parallel if they have no dependency due to how spark works.
Parallel outputting is currently not supported, because we are running a single spark job per metorikku file.
I don't think spark can do this in parallel in a single spark job context.
