### ISSUE TITLE
Support loading config files from HDFS

### ISSUE THREAD

**Issue by lyogev** [YotpoLtd/metorikku#142]
This is a very simple fix that can help with some use cases.
Just switch loading the files to use org.apache.hadoop.fs classes.

**Comment by tooptoop4** [comment]
@lyogev any update on this?

**Comment by lyogev** [comment]
Actually no. we actually don't intend to support this for now, we don't have a need for it.
You are more than welcome to contribute!

**Comment by tooptoop4** [comment]
does https://github.com/YotpoLtd/metorikku/pull/329 fix this?

**Comment by lyogev** [comment]
Yes actually. closing 👍
