### ISSUE TITLE
api get/post input support

### ISSUE THREAD

**Issue by tooptoop4** [YotpoLtd/metorikku#152]
would be great to be able to specify something like a curl request to a simple GET http endpoint (and later POST params) and the results feeding into a metorikku input

**Comment by lyogev** [comment]
Do you mean to add a writer that outputs to some restful API?

**Comment by tooptoop4** [comment]
no, i mean specify input value in the yaml as GET 'https://jsonplaceholder.typicode.com/posts?userId=1' then in a metric i could export to any normal output like csv,parqueet,jdbc.etc Key thing is the input is the results from a API url. I guess at first can make req that the API results must be in json format
