### ISSUE TITLE
log df.count of input/metric/output dataframes

### ISSUE THREAD

**Issue by tooptoop4** [YotpoLtd/metorikku#160]
For each input, metric, output would be great to log the count of rows processed. ie if input csv had 100 rows then spark log to show input<abc name> 100 rows, then if metric had some where filter log metric<xyz name> 47 rows..eetc

**Comment by lyogev** [comment]
We report counts for processed outputs with instrumentation and we can add logs of course.
For all other use cases I wouldn't want to burden the process with counts that I don't need as these are very expensive.
