### ISSUE TITLE
Cassandra Input & Output

### ISSUE THREAD

**Issue by pacific28** [YotpoLtd/metorikku#167]
Hi,
Found this great tool. It seems to be very good in first impression. I was trying this tool to migrate my data from one Cassandra to another Cassandra cluster.  
I had setup spark and running metorikku in spark. Everything seems to be fine expect i'm getting this error:
__**Caused by: org.apache.spark.sql.catalyst.analysis.NoSuchTableException: Table or view 'role' not found in database 'default';_**_

I'm using metic config as:
=========================
steps:
  - dataFrameName: role
    sql:
      SELECT * FROM role
    ignoreOnFailures: true
output:
  - dataFrameName: role
    outputType: Cassandra
    outputOptions:
      saveMode: Overwrite
      dbKeySpace: collector
      dbTable: role
==================================

Please help me with this. 
PS: i'm new to spark. 

Thanks!!

**Comment by lyogev** [comment]
Hi!
Can you share your job configuration as well?

Thanks

**Comment by pacific28** [comment]
metrics:
  - /home/guptaprashan01/Hari_Workspace/metric.yaml

# Input configuration
inputs:
  input_6:
    cassandra:
      host: 100.85.93.12
      table: role
      keySpace: collector_test

output:
  # cassandra Database arguments: host is mandatory. username and password are supported
  cassandra:
    host: 100.85.93.2
  # Output file directory
  file:
    dir: /home/pacific/Hari_Workspace/result.out

# If set to true, triggers Explain before saving
explain: true

# Shows a Preview of the output
showPreviewLines: 42

# Prints the query after running it
showQuery: true

# Caches the step before each preview
cacheOnPreview: true

# Set Log Level : ALL, DEBUG, ERROR, FATAL, INFO, OFF, TRACE, WARN
logLevel: WARN

# Set Application Name to have app name prefix in spark instrumentation counters
#appName: appName

**Comment by lyogev** [comment]
In the job configuration you called your role table input_6 so in the metric config you need to write the SQL: select * from input_6

**Comment by pacific28** [comment]
i'm bit confused, input_6 is the name of input, just representational Or it is name of table.

**Comment by lyogev** [comment]
Metorikku is based on giving logical names to inputs.
You gave your Cassandra input the name input_6 so in your SQL you need to reference using this name

**Comment by pacific28** [comment]
@lyogev 
Thanks a lot!! Its working.

Great tool!!

**Comment by lyogev** [comment]
Glad I could help!
