### ISSUE TITLE
feature req - 'deequ' (data quality) integration

### ISSUE THREAD

**Issue by tooptoop4** [YotpoLtd/metorikku#191]
https://aws.amazon.com/blogs/big-data/test-data-quality-at-scale-with-deequ/
https://github.com/awslabs/deequ

This feature is about new config flags in yaml so metorikku can integrate with deequ to:
1. output Data analysis metrics like ApproxCountDistinct, Mean.etc
2. run 'unit tests for data' .ie ComplianceConstraint

**Comment by lyogev** [comment]
Very cool idea. project seems super simple and fits metorikku well. Would love your contribution here!

**Comment by dtsylyuryk** [comment]
Wanna work with this.

**Comment by RonBarabash** [comment]
added
