### ISSUE TITLE
feature req - 'spline' (data lineage) integration

### ISSUE THREAD

**Issue by tooptoop4** [YotpoLtd/metorikku#192]
https://absaoss.github.io/spline/

This feature is about new config flags in yaml so metorikku can integrate with spline to output lineage information between input->metric(s) and metric->metric(s)

ie columnA * columnB from inputX   ---> columnC in metricY

**Comment by RonBarabash** [comment]
@tooptoop4 we have added apache atlas integration which also support data lineage,
check it out to see if it fits your needs,
