### ISSUE TITLE
Hudi: Output to S3 bucket

### ISSUE THREAD

**Issue by Rap70r** [YotpoLtd/metorikku#241]
Hello,

Is it possible for hudi to write to S3 bucket instead to a local folder?
When the output is hudi, is it possible to set S3 bucket for dir parameter?
Setting S3 bucket for dir parameter it gives the following error:

Class org.apache.hadoop.fs.s3a.S3AFileSystem not found

Thank you

**Comment by lyogev** [comment]
Yes definately possible.
Since you are using the standalone metorikku (saw from another issue) you need to provide your own hadoop AWS jars.
Metorikku standalone is mostly used for tests and running locally so we never included the hadoop AWS jars.
Download the following:
http://central.maven.org/maven2/com/amazonaws/aws-java-sdk/1.7.4/aws-java-sdk-1.7.4.jar
http://central.maven.org/maven2/org/apache/hadoop/hadoop-aws/2.7.3/hadoop-aws-2.7.3.jar

And put them somewhere.
Then in your command do something like:
```java -Dspark.master=local[*] -cp metorikku-standalone.jar:/path/to/aws-java-sdk-1.7.4.jar:/path/to/hadoop-aws-2.7.3.jar```

**Comment by Rap70r** [comment]
Hi lyogev,

I added those jar files to the class path, but it's giving the following error:

java.lang.NumberFormatException: For input string: "100M"

I think it has to do with the compatibility between aws-java-sdk-1.7.4.jar and hadoop-aws-2.7.1.jar.
I'm trying different versions of hadoop-aws.

Thank you

**Comment by lyogev** [comment]
Should be ```hadoop-aws-2.7.3.jar```

**Comment by Rap70r** [comment]
Hi lyogev,

I had to pass couple of arguments to make it work, but, yeah, it uses hadoop-aws-2.7.3.jar. :)
By the way, do you know why, when the output is hudi, it stores the data set in both hive and S3? Why there is a need for hive storage if the data is in S3?

Thank you

**Comment by lyogev** [comment]
Glad that it's working for you.
Can you send your final command? Just so we'll have a reference.

Regarding hive, it's not actually saving the data in hive, its just adding references to it. It uses hive to store locations of all the partitions etc.
But as I said before you don't have to use hive you can disable the hive sync .

**Comment by Rap70r** [comment]
Hi lyogev,

Sure. Here is the final command:

java -Dspark.master=local[*] -Dspark.serializer=org.apache.spark.serializer.KryoSerializer -Dspark.hadoop.hive.metastore.uris=thrift://localhost:9083 -Dspark.sql.catalogImplementation=hive -Dspark.hadoop.fs.s3a.multipart.size=104857600 -Dspark.hadoop.fs.s3a.threads.max=256 -Dspark.hadoop.fs.defaultFS=s3a://bucket_name -Dspark.hadoop.fs.s3.impl=org.apache.hadoop.fs.s3a.S3AFileSystem -Dspark.hadoop.fs.s3a.block.size=33554432 -cp datanucleus-core-3.2.10.jar:datanucleus-api-jdo-3.2.8.jar:datanucleus-rdbms-3.2.9.jar:aws-java-sdk-1.7.4.jar:hadoop-aws-2.7.3.jar:metorikku-standalone.jar com.yotpo.metorikku.Metorikku -c config.yaml

I appreciate the help.

By the way, just in case you might know. I'm trying to figure out an issue when the source field is a decimal type.
I'm getting this error:
com.databricks.spark.avro.SchemaConverters$IncompatibleSchemaException: Cannot convert Avro schema to catalyst type because schema at path before.some_field_name is not compatible (avroType = DecimalType(16,4), sqlType = BYTES).

Have you seen this before?

Thank you
