### ISSUE TITLE
cache input?

### ISSUE THREAD

**Issue by tooptoop4** [YotpoLtd/metorikku#242]
I read a 1.3GB input csv.gz (25gb uncompressed, 86mn rows) and then run 4 metric SQLs on it. It takes 16hrs

Would an option to add df.cache at line 30 below work?

https://github.com/YotpoLtd/metorikku/blob/master/src/main/scala/com/yotpo/metorikku/input/readers/file/FilesInput.scala#L30

**Comment by giladw** [comment]
You can do inside the metric, just add a step with lazy cache:
- dataFrameName: df_cached
  sql:
    CACHE LAZY TABLE table_name


you can read more about it here:
https://docs.databricks.com/spark/latest/spark-sql/language-manual/cache-table.html

**Comment by tooptoop4** [comment]
@giladw    after using your suggestion i see only single read from s3 which is good but overall time is still the same, i see a lot of time is spent in https://github.com/YotpoLtd/metorikku/blob/v0.0.47/src/main/scala/com/yotpo/metorikku/metric/Metric.scala#L86 - how to turn off instrumentation? i asked on https://github.com/YotpoLtd/metorikku/issues/76

**Comment by lyogev** [comment]
To turn off counting and instrumentation add the following to your job file:
```
cacheCountOnOutput: false
```

Please note that this was added in version 0.0.50

**Comment by tooptoop4** [comment]
but instrumentation will still be in places like https://github.com/YotpoLtd/metorikku/blob/9e1b842c7cacb46394cec677c7dd8c6b28d14e47/src/main/scala/com/yotpo/metorikku/metric/MetricSet.scala#L49. ? @lyogev

**Comment by lyogev** [comment]
It's not a problem, it's not doing anything special, just notifying that the dag started.
