### ISSUE TITLE
Continuous Processing Mode When Source is Kafka

### ISSUE THREAD

**Issue by Rap70r** [YotpoLtd/metorikku#260]
Hello,

Is it possible to enable streaming mode that will process changes to the output automatically whenever there are changes available in kafka, without running spark submit in interval mode.

Thank you

**Comment by lyogev** [comment]
Of course! check out https://github.com/YotpoLtd/metorikku#streaming-input

**Comment by Rap70r** [comment]
Hi lyogev,

Thank you for getting back to me. That was very helpful.
