### ISSUE TITLE
How to install and use Schema Registry?

### ISSUE THREAD

**Issue by Rap70r** [YotpoLtd/metorikku#268]
Hello,

I have a Kafka setup that outputs to hudi. I need to use Schema Registry. Do I have to build a development version of Schema Registry or is there a package I can use that includes the Schema Registry?

Thank you

**Comment by lyogev** [comment]
Check out the docker-compose here:
https://github.com/YotpoLtd/metorikku/blob/master/e2e/cdc/docker-compose.yml

You can see how we are starting the schema registry and how we connect to it.

**Comment by Rap70r** [comment]
Hi lyogev,

Thank you for getting back to me.
I saw that section that uses the following: confluentinc/cp-schema-registry. But my setup is not using Docker at all. I was wondering if there's a way to install Schema Registry or use a standalone jar of it.

Thank you

**Comment by Rap70r** [comment]
Hi lyogev,

I think I figured it out.

Thank you
