### ISSUE TITLE
Can the same jar file be used by multiple spark submit commands?

### ISSUE THREAD

**Issue by Rap70r** [YotpoLtd/metorikku#273]
Hello,

Is it possible to run multiple spark submit commands simultaneously using the same metorikku.jar file?
I tried running 2 spark submit commands, pointing to the jar file, on an emr cluster but only the first one was syncing.

Thank you

**Comment by lyogev** [comment]
It really depends on your cluster configuration, for example,  if you're running using yarn and your cluster has dynamicallocation on then you can run multiple jobs under the same cluster.
So it's not a metorikku feature, but a spark feature.

**Comment by lyogev** [comment]
If you're using EMR, you need to make sure the job is not getting all the resources (executor/driver.memory)

**Comment by Rap70r** [comment]
Thank you, lyogev.
You're right, the resources were being consumed by the first spark job.
