### ISSUE TITLE
How to disable hive sync when the output is hudi?

### ISSUE THREAD

**Issue by Rap70r** [YotpoLtd/metorikku#274]
Hello,

is there a way to disable hive sync when the output is hudi? I tried removing tableName from the metric file but spark gave me an error saying: "'hoodie.table.name', 'path' must be set"
I also tried setting the following:

>   extraOptions:
    hoodie.table.name: test

but I got the same error.
Is there a way to disable hive sync?

Thank you

**Comment by lyogev** [comment]
If you're in the job.yaml add:
```options:
           hoodie.datasource.hive_sync.enable: false```

**Comment by Rap70r** [comment]
Hi lyogev,

Thank you for getting back to me.
Just a clarification. When you say job.yaml you mean _config.yaml, right?
In that case, that option should go under output, like the following:

> output:
  hudi:
    dir: s3://some_bucket
    operation: upsert
    storageType: COPY_ON_WRITE
    maxVersions: 1
  options:
    hoodie.datasource.hive_sync.enable: false

Right?

Thank you

**Comment by lyogev** [comment]
Yes that one.

**Comment by Rap70r** [comment]
Hi lyogev,

I have set that, but I think tableName is mandatory in the metric file. Otherwise I get that error above.

Thank you

**Comment by lyogev** [comment]
You still need the tablename (it's a must for hudi), but the other config disables the hive sync

**Comment by Rap70r** [comment]
Got it. Thank you for the help.
