### ISSUE TITLE
Error: ClassNotFoundException: org.apache.hudi.common.model.OverwriteWithLatestAvroPayload

### ISSUE THREAD

**Issue by Rap70r** [YotpoLtd/metorikku#295]
Hello,

I'm getting an error using the latest version:

> ClassNotFoundException: org.apache.hudi.common.model.OverwriteWithLatestAvroPayload

Can you please help?

Thank you

**Comment by lyogev** [comment]
Are you using Hudi?

**Comment by Rap70r** [comment]
Hi lyogev,

Yes. And I'm passing hoodie_spark_bundle.jar to the class path. This works fine with older versions of Metorikku. Latest version is throwing the error.
Was anything changed?

Thank you

**Comment by Rap70r** [comment]
Hello,

It was something in my configuration. I managed to get it working. 

Thank you
