### ISSUE TITLE
How to use multiple jdbc connections?

### ISSUE THREAD

**Issue by akizminet** [YotpoLtd/metorikku#413]
Hello. How can I use multiple jdbc connections?

**Comment by lyogev** [comment]
You can use the named outputs feature https://github.com/YotpoLtd/metorikku/blob/59d2bd12c1f882c96f1f9421cd18aedbda021cd9/config/job_config_sample.yaml#L145

**Comment by akizminet** [comment]
> You can use the named outputs feature
> 
> https://github.com/YotpoLtd/metorikku/blob/59d2bd12c1f882c96f1f9421cd18aedbda021cd9/config/job_config_sample.yaml#L145

Thank you.
